### ISSUE TITLE
Select in Fleet

### ISSUE THREAD

**Issue by pjank42** [TheAirlineProject/tap-desktop#326]
Do you think a select all of 'XXXXX' Aircraft type action button (or a show certain aircraft filter like on the leasing page) can be done for fleet editing? Eventually you end up with a massive fleet or numerous aircraft types and it can be very time consuming to find the aircraft you're trying to edit

**Comment by dmks1234** [comment]
Yes that would be great however I would like a drag and drop type thing to try and move aircraft around .
