### ISSUE TITLE
Unrealistic passenger behaviour at extreme prices.

### ISSUE THREAD

**Issue by benceboc** [TheAirlineProject/tap-desktop#346]
Game version: 0.4.2 pre 5

If you change an already working routes pricing to any extremely high value (eg. from $30 to $30000), you will still get some passengers on your flights, which of course will leave you with tons of money for only 1 route.

**Comment by mh25** [comment]
where did you download that version from?

**Comment by benceboc** [comment]
http://www.theairlineproject.com/forum/showthread.php?542-0-4-2-Prealpha/page11

**Comment by pjank42** [comment]
Good point which will be fixed before next release
