### ISSUE TITLE
4 classes, but only 3 assignable

### ISSUE THREAD

**Issue by mh25** [TheAirlineProject/tap-desktop#348]
There are now 4 classes available for planes, but you can only assign (a maximum of) 3 of them to any given plane.   For example, if you go to configure an A380 on ordering, you can assign a second class to first, business, or premium economy.  However, if you go to add a 3rd, you can't select what type of class that is and there's no option to add a fourth class.

Also, there is no way to have a plane without economy class, altogether (which would be useful for a concorde -- all first class)

**Comment by pjank42** [comment]
The only aircraft we have which can have 4 classes is Airbus A350-1000. This is because most aircrafts usually uses the premium economy as a replacement for one of the other classes

**Comment by mh25** [comment]
There are other aircraft with 4 classes.  British Airways does it on their 747 (http://www.seatguru.com/airlines/British_Airways/British_Airways_Boeing_747-400_C.php), A380, and 777.  Air France has 4 classes on A380s and 777s.  

That's not really the problem, though.  The problem is that there's really no way, now, to provision an aircraft @ purchase from manufacturer with the 3 standard classes:  economy, business and first.  If you choose "business" (or "first-class") for class 2, and then add a third class, it auto adds as "premium economy".  The third class added needs to be changeable.  (and the default single-class should be changeable, too, if you want to run an aircraft with all "first class" or "business" seats)

**Comment by pjank42** [comment]
I have now fixed so you also can select economy premium from manufacturer as well as an first class / business class only aircraft
