### ISSUE TITLE
Route map

### ISSUE THREAD

**Issue by pjank42** [TheAirlineProject/tap-desktop#350]
The route map should not show the route from SEA to Japan over Europe

**Comment by Matt-Jackson** [comment]
Can we not use the old system?

**Comment by pjank42** [comment]
I got the solution for the new map system, so I just need to implement it

**Comment by Matt-Jackson** [comment]
Nice one, can I ask what it involves?

**Comment by pjank42** [comment]
Just a matter of changing the calculation so instead of using a negative value for ex. the us airports we should use 180 + the value for the cases where the route should go west instead of east

**Comment by pjank42** [comment]
No I just need to figure out when an airliner will travel east and when it will travel west

**Comment by pjank42** [comment]
Should be ok
