### ISSUE TITLE
Problems saving

### ISSUE THREAD

**Issue by TheRealBlackIce** [TheAirlineProject/tap-desktop#358]
Hey guys, just letting you know that from the time I first found this (about a year ago i think), and to the latest update. I have always had difficulty saving any game. It would always show "Saving..." with the spinning thing and never stop untill I closed the application. And sometimes when I loaded it later, it would load some random airline company (most of the time using a custom airline). I have tried running with compatibility for win7, xp, etc. and I have also changed the permissions so that the application could do whatever it wanted.
Overall I love this airline simulator and I believe it is the best, and also making offline makes it that so much more.
Thanks for your support.

BlackIce.

**Comment by Matt-Jackson** [comment]
Hi BlackIce, cheers for joining us.

Do you have any more information such as the details of your system, what set-up you are playing as and how often you try to save?  Where are the program files located?  I've never heard of this problem, although I'm aware that it tends to take quite a long time to save depending on how far you are in.

If I could as that you try the following;
1. Start a new scenario ("New Management" for example).
2. Once it's loaded, let it run for a few days in-game time without doing anything.
3. Pause the game. Then attempt to save.  It should take no longer than a minute.

Let us know how you get on.  Step-by-step is the way!

Matthew

**Comment by TheRealBlackIce** [comment]
I am running TAP on a ASUS X401. The basic specs: 2.4Ghz dual core Pentium, 4Gb RAM and running Windows 8.
Most of the time in TAP, I normally make a custom airline, save it (no problems) and then use it straight away. I normally setup regional/domestic airlines within Australia. I normally go max competitor airlines which ends up about 5.
I normally don't have much time to play so I think I might be trying to save every 10-20 minutes.
I have the "tap0394" folder directly in my Data (D) drive and my saves seem to go to my documents.
You never know I might just have to wait a bit longer for it to save, but sometimes I have let it go for at least 5 minutes.
I will try your method and let you know how it goes soon.

Hope this helps.
Thanks. Luke.

**Comment by TheRealBlackIce** [comment]
Ok Matt, I just tried your method and it did the same thing.
no change.
BlackIce

**Comment by pjank42** [comment]
Fixed for next release
