### ISSUE TITLE
Game Lock up

### ISSUE THREAD

**Issue by jkamp757** [TheAirlineProject/tap-desktop#359]
I am a new user, using 0.3.9.4. Everything goes fine for about 18 months. Then the game comes to a halt and the only way I can get it to advance is to pause the game and then unpause it. This causes the game to advance one day, then I must pause and unpause again. This works for about a week then the game goes unresponsive, and must be closed. This has happened in both games I have played so far.

**Comment by Matt-Jackson** [comment]
Hi KJamp,

Again, please use the latest version as supplied in the other issue thread.  This issue should be solved in the current version.

Cheers!
