### ISSUE TITLE
Double lease planes

### ISSUE THREAD

**Issue by jkamp757** [TheAirlineProject/tap-desktop#360]
Using 0.3.9.4 I started a new game as Delta in 1970. I went in to the Used Airliners screen to lease some planes. I checked 5 707-320Bs, and 3 737-200s, and clicked Lease Plane Buttons.

When I looked at the Fleet, I had 10 707-320Bs and 6 737-200s in the fleet, and each serial number (N-001, N-002, ect.) was listed twice. I was able to schedule all the planes with n problem.

**Comment by pjank42** [comment]
Have you tried the latest version since we are currently on 042 RC?

**Comment by jkamp757** [comment]
I tried downloading the latest version but got 404 errors.

**Comment by Matt-Jackson** [comment]
Hi JKamp,
Download x64 here: http://www.theairlineproject.com/ccount/click.php?id=57
Download x86 here: http://www.theairlineproject.com/ccount/click.php?id=58

If you can try and replicate the problem using the current version and report back if it's still causing you any issues; this shouldn't be happening in the current version.  I'll close the issue for now.

**Comment by jkamp757** [comment]
Sorry I thought I had the latest version. I have 042 now and it's working much better.

**Comment by pjank42** [comment]
:-)
