### ISSUE TITLE
can't perform maintenance

### ISSUE THREAD

**Issue by mh25** [TheAirlineProject/tap-desktop#364]
When you save a game, then come back to it later and re-load it, maintenance doesn't work on planes you already own.

A second set of "check" options appears below the first, and entering maintenance facilities in there doesn't "stick" (i.e, leave and come back and the maintenance options will be gone).  Eventually, the plane will be grounded because of maintenance.  The only real option is to sell and re-buy the plane or just otherwise replace it.  (rc7b)

**Comment by pjank42** [comment]
This one should be ok now
